// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoutubeDownloader.Database;

namespace YoutubeDownloader.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200405211231_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("YoutubeDownloader.Database.Models.DownloadFolder", b =>
                {
                    b.Property<int>("DownloadFolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSelectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.HasKey("DownloadFolderId");

                    b.ToTable("DownloadFolders");
                });

            modelBuilder.Entity("YoutubeDownloader.Database.Models.HistoryRecord", b =>
                {
                    b.Property<int>("HistoryRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DownloadDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadFormat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DownloadStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("HistoryRecordId");

                    b.ToTable("History");
                });
#pragma warning restore 612, 618
        }
    }
}
