//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Downloader.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bin.
        /// </summary>
        public static string BinDirectoryName {
            get {
                return ResourceManager.GetString("BinDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseButtonText {
            get {
                return ResourceManager.GetString("BrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearButtonText {
            get {
                return ResourceManager.GetString("ClearButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffmpeg.
        /// </summary>
        public static string ConverterDirectoryName {
            get {
                return ResourceManager.GetString("ConverterDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube-dl.exe.
        /// </summary>
        public static string DownloaderFileName {
            get {
                return ResourceManager.GetString("DownloaderFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio only.
        /// </summary>
        public static string DownloaderFormatAudioOnlyName {
            get {
                return ResourceManager.GetString("DownloaderFormatAudioOnlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best quality video available by direct link.
        /// </summary>
        public static string DownloaderFormatBestDirectLinkName {
            get {
                return ResourceManager.GetString("DownloaderFormatBestDirectLinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best quality video.
        /// </summary>
        public static string DownloaderFormatBestName {
            get {
                return ResourceManager.GetString("DownloaderFormatBestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(title)s.%(ext)s.
        /// </summary>
        public static string DownloaderItemTitleTemplate {
            get {
                return ResourceManager.GetString("DownloaderItemTitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --ffmpeg-location.
        /// </summary>
        public static string DownloaderOptionConverterLocation {
            get {
                return ResourceManager.GetString("DownloaderOptionConverterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --encoding utf-8.
        /// </summary>
        public static string DownloaderOptionEncodingUtf8 {
            get {
                return ResourceManager.GetString("DownloaderOptionEncodingUtf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp3/ogg/m4a/aac.
        /// </summary>
        public static string DownloaderOptionFormatAudioOnly {
            get {
                return ResourceManager.GetString("DownloaderOptionFormatAudioOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best.
        /// </summary>
        public static string DownloaderOptionFormatBest {
            get {
                return ResourceManager.GetString("DownloaderOptionFormatBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (bestvideo+bestaudio/best)[protocol^=http].
        /// </summary>
        public static string DownloaderOptionFormatBestDirectLink {
            get {
                return ResourceManager.GetString("DownloaderOptionFormatBestDirectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --get-filename.
        /// </summary>
        public static string DownloaderOptionGetFilename {
            get {
                return ResourceManager.GetString("DownloaderOptionGetFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --no-mtime.
        /// </summary>
        public static string DownloaderOptionNoOriginalDateTime {
            get {
                return ResourceManager.GetString("DownloaderOptionNoOriginalDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --no-playlist.
        /// </summary>
        public static string DownloaderOptionNoPlaylist {
            get {
                return ResourceManager.GetString("DownloaderOptionNoPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --retries.
        /// </summary>
        public static string DownloaderOptionRetries {
            get {
                return ResourceManager.GetString("DownloaderOptionRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --socket-timeout.
        /// </summary>
        public static string DownloaderOptionSocketTimeout {
            get {
                return ResourceManager.GetString("DownloaderOptionSocketTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the download folder:.
        /// </summary>
        public static string DownloadFolderCaption {
            get {
                return ResourceManager.GetString("DownloadFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what you want to download:.
        /// </summary>
        public static string DownloadFormatCaption {
            get {
                return ResourceManager.GetString("DownloadFormatCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put link to a video here:.
        /// </summary>
        public static string DownloadLinkCaption {
            get {
                return ResourceManager.GetString("DownloadLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explorer.exe.
        /// </summary>
        public static string ExplorerFileName {
            get {
                return ResourceManager.GetString("ExplorerFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /select.
        /// </summary>
        public static string ExplorerOptionSelect {
            get {
                return ResourceManager.GetString("ExplorerOptionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have cancelled the download..
        /// </summary>
        public static string LogMessageDownloadCancel {
            get {
                return ResourceManager.GetString("LogMessageDownloadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed..
        /// </summary>
        public static string LogMessageDownloadFail {
            get {
                return ResourceManager.GetString("LogMessageDownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the file: {0}
        ///Link: {1}.
        /// </summary>
        public static string LogMessageDownloadingFile {
            get {
                return ResourceManager.GetString("LogMessageDownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to download your files....
        /// </summary>
        public static string LogMessageDownloadStart {
            get {
                return ResourceManager.GetString("LogMessageDownloadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! Your download successfully completed!.
        /// </summary>
        public static string LogMessageDownloadSuccess {
            get {
                return ResourceManager.GetString("LogMessageDownloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name successfully retrieved: {0}.
        /// </summary>
        public static string LogMessageFileNameRetrieved {
            get {
                return ResourceManager.GetString("LogMessageFileNameRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may find your file here: {0}.
        /// </summary>
        public static string LogMessageLocationOfFile {
            get {
                return ResourceManager.GetString("LogMessageLocationOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may find your files here: {0}.
        /// </summary>
        public static string LogMessageLocationOfFiles {
            get {
                return ResourceManager.GetString("LogMessageLocationOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete!.
        /// </summary>
        public static string MessageDownloadComplete {
            get {
                return ResourceManager.GetString("MessageDownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading: {0}.
        /// </summary>
        public static string MessageDownloading {
            get {
                return ResourceManager.GetString("MessageDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to download....
        /// </summary>
        public static string MessageDownloadPreparing {
            get {
                return ResourceManager.GetString("MessageDownloadPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (\[download\]\s*)(\S*)(\s*)% of.
        /// </summary>
        public static string SearchPatternDownloadProgress {
            get {
                return ResourceManager.GetString("SearchPatternDownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show downloaded items.
        /// </summary>
        public static string ShowDownloadedItemsButtonText {
            get {
                return ResourceManager.GetString("ShowDownloadedItemsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log.
        /// </summary>
        public static string ShowLogExpanderText {
            get {
                return ResourceManager.GetString("ShowLogExpanderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download!.
        /// </summary>
        public static string StartDownloadButtonText {
            get {
                return ResourceManager.GetString("StartDownloadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop!.
        /// </summary>
        public static string StopDownloadButtonText {
            get {
                return ResourceManager.GetString("StopDownloadButtonText", resourceCulture);
            }
        }
    }
}
