//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Downloader.
        /// </summary>
        public static string AppFolderName {
            get {
                return ResourceManager.GetString("AppFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Downloader.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseButtonText {
            get {
                return ResourceManager.GetString("BrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearButtonText {
            get {
                return ResourceManager.GetString("ClearButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.db.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DataFolderName {
            get {
                return ResourceManager.GetString("DataFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio only.
        /// </summary>
        public static string DownloaderFormatAudioOnlyName {
            get {
                return ResourceManager.GetString("DownloaderFormatAudioOnlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best quality video available by direct link.
        /// </summary>
        public static string DownloaderFormatBestDirectLinkName {
            get {
                return ResourceManager.GetString("DownloaderFormatBestDirectLinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best quality MP4 video.
        /// </summary>
        public static string DownloaderFormatBestMp4Name {
            get {
                return ResourceManager.GetString("DownloaderFormatBestMp4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best quality video.
        /// </summary>
        public static string DownloaderFormatBestName {
            get {
                return ResourceManager.GetString("DownloaderFormatBestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the download folder:.
        /// </summary>
        public static string DownloadFolderCaption {
            get {
                return ResourceManager.GetString("DownloadFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what you want to download:.
        /// </summary>
        public static string DownloadFormatCaption {
            get {
                return ResourceManager.GetString("DownloadFormatCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put link to a video here:.
        /// </summary>
        public static string DownloadLinkCaption {
            get {
                return ResourceManager.GetString("DownloadLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DownloadStatusCancel {
            get {
                return ResourceManager.GetString("DownloadStatusCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string DownloadStatusFail {
            get {
                return ResourceManager.GetString("DownloadStatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string DownloadStatusSuccess {
            get {
                return ResourceManager.GetString("DownloadStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string DownloadStatusUnknown {
            get {
                return ResourceManager.GetString("DownloadStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explorer.exe.
        /// </summary>
        public static string ExplorerFileName {
            get {
                return ResourceManager.GetString("ExplorerFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /select.
        /// </summary>
        public static string ExplorerOptionSelect {
            get {
                return ResourceManager.GetString("ExplorerOptionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History.
        /// </summary>
        public static string HistoryMenuItemClearHistory {
            get {
                return ResourceManager.GetString("HistoryMenuItemClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Download Link.
        /// </summary>
        public static string HistoryMenuItemCopyLink {
            get {
                return ResourceManager.GetString("HistoryMenuItemCopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Download Folder.
        /// </summary>
        public static string HistoryMenuItemOpenFolder {
            get {
                return ResourceManager.GetString("HistoryMenuItemOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redownload.
        /// </summary>
        public static string HistoryMenuItemReDownload {
            get {
                return ResourceManager.GetString("HistoryMenuItemReDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From History.
        /// </summary>
        public static string HistoryMenuItemRemoveFromHistory {
            get {
                return ResourceManager.GetString("HistoryMenuItemRemoveFromHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string LogFolderName {
            get {
                return ResourceManager.GetString("LogFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have cancelled the download..
        /// </summary>
        public static string LogMessageDownloadCancel {
            get {
                return ResourceManager.GetString("LogMessageDownloadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed..
        /// </summary>
        public static string LogMessageDownloadFail {
            get {
                return ResourceManager.GetString("LogMessageDownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the file: {0}
        ///Url: {1}.
        /// </summary>
        public static string LogMessageDownloadingFile {
            get {
                return ResourceManager.GetString("LogMessageDownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to download your files....
        /// </summary>
        public static string LogMessageDownloadStart {
            get {
                return ResourceManager.GetString("LogMessageDownloadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! Your download successfully completed!.
        /// </summary>
        public static string LogMessageDownloadSuccess {
            get {
                return ResourceManager.GetString("LogMessageDownloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name successfully retrieved: {0}.
        /// </summary>
        public static string LogMessageFileNameRetrieved {
            get {
                return ResourceManager.GetString("LogMessageFileNameRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may find your file here: {0}.
        /// </summary>
        public static string LogMessageLocationOfFile {
            get {
                return ResourceManager.GetString("LogMessageLocationOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may find your files here: {0}.
        /// </summary>
        public static string LogMessageLocationOfFiles {
            get {
                return ResourceManager.GetString("LogMessageLocationOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolfcub.
        /// </summary>
        public static string ManufacturerFolderName {
            get {
                return ResourceManager.GetString("ManufacturerFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download cancelled! {0}.
        /// </summary>
        public static string MessageDownloadCancelled {
            get {
                return ResourceManager.GetString("MessageDownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete! {0}.
        /// </summary>
        public static string MessageDownloadComplete {
            get {
                return ResourceManager.GetString("MessageDownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed! {0}.
        /// </summary>
        public static string MessageDownloadFailed {
            get {
                return ResourceManager.GetString("MessageDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading:.
        /// </summary>
        public static string MessageDownloading {
            get {
                return ResourceManager.GetString("MessageDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to download....
        /// </summary>
        public static string MessageDownloadPreparing {
            get {
                return ResourceManager.GetString("MessageDownloadPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the downloader....
        /// </summary>
        public static string MessageUpdatingDownloader {
            get {
                return ResourceManager.GetString("MessageUpdatingDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show downloaded items.
        /// </summary>
        public static string ShowDownloadedItemsButtonText {
            get {
                return ResourceManager.GetString("ShowDownloadedItemsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show History.
        /// </summary>
        public static string ShowHistoryExpanderText {
            get {
                return ResourceManager.GetString("ShowHistoryExpanderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log.
        /// </summary>
        public static string ShowLogExpanderText {
            get {
                return ResourceManager.GetString("ShowLogExpanderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download!.
        /// </summary>
        public static string StartDownloadButtonText {
            get {
                return ResourceManager.GetString("StartDownloadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop!.
        /// </summary>
        public static string StopDownloadButtonText {
            get {
                return ResourceManager.GetString("StopDownloadButtonText", resourceCulture);
            }
        }
    }
}
