<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediaDownloader.Data\MediaDownloader.Data.csproj" />
    <ProjectReference Include="..\MediaDownloader.Download\MediaDownloader.Download.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="TestData\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
